import type { Column, Relation, Schema, Table } from '@schemalens/schema-core';
import { SQL_DIALECT_MAP } from './dialects';
import type { SqlDialect, SqlDialectId } from './types';

/**
 * DSL 的 defaultValue 只存原始文字，沒有保留「是字串/數字/函式呼叫」這個資訊，
 * 這裡用啟發式規則猜：純數字、true/false/null、CURRENT_* 關鍵字、看起來像函式呼叫
 * （以 `)` 結尾）就照抄，其餘當成字串字面值加單引號。不是型別安全的判斷，
 * 匯出後建議使用者自己看一眼。
 *
 * CURRENT_DATE/CURRENT_TIME/CURRENT_TIMESTAMP 是 SQL 標準關鍵字、不是函式，
 * 來源文字裡常見誤寫成 `CURRENT_DATE()` 這種函式呼叫形式——這種寫法在 PostgreSQL/SQLite
 * 是無效語法（不接受空括號），所以這裡一律去掉多餘的空括號，統一輸出成裸關鍵字，
 * 這在四種支援的方言裡都合法（MySQL 兩種寫法都接受）。
 */
function renderDefaultLiteral(raw: string): string {
	const value = raw.trim();
	if (/^-?\d+(\.\d+)?$/.test(value)) return value;
	if (/^(true|false|null)$/i.test(value)) return value.toUpperCase();
	if (/^current_(timestamp|date|time)(\(\))?$/i.test(value)) return value.replace(/\(\)$/, '').toUpperCase();
	if (value.endsWith(')')) return value;
	return `'${value.replace(/'/g, "''")}'`;
}

function renderColumnDef(dialect: SqlDialect, column: Column): string {
	const parts = [dialect.quoteIdentifier(column.name), dialect.renderType(column)];
	if (!column.nullable) parts.push('NOT NULL');
	if (column.defaultValue !== undefined) parts.push(`DEFAULT ${renderDefaultLiteral(column.defaultValue)}`);
	if (column.unique) parts.push('UNIQUE');
	return parts.join(' ');
}

function renderForeignKeyClause(dialect: SqlDialect, relation: Relation, targetTable: Table | undefined): string {
	const cols = relation.sourceColumns.map((c) => dialect.quoteIdentifier(c)).join(', ');
	const refCols = relation.targetColumns.map((c) => dialect.quoteIdentifier(c)).join(', ');
	const targetName = targetTable ? dialect.qualifyTableName(targetTable) : dialect.quoteIdentifier(relation.targetTable);
	return `FOREIGN KEY (${cols}) REFERENCES ${targetName} (${refCols})`;
}

/**
 * 兩種方言（MySQL/MSSQL）一律把外鍵放到最後用 ALTER TABLE 補上，
 * SQLite 一律 inline 寫在 CREATE TABLE 裡——藉此完全避開「表跟表互相依賴，
 * 該先建哪張表」的 topological sort 問題：
 * - ALTER TABLE 版本：所有 CREATE TABLE 都先跑完，此時外鍵指到誰都沒差。
 * - SQLite inline 版本：SQLite 本來就不會在 CREATE TABLE 當下驗證被參照的表是否存在。
 *
 * DSL 的 Column 沒有 auto-increment / identity 的欄位，所以這裡刻意不生成
 * AUTO_INCREMENT / IDENTITY(1,1) 之類的東西——寧可少做，也不要憑空腦補語意。
 */
export function renderSchemaAsSql(schema: Schema, dialectId: SqlDialectId): string {
	const dialect = SQL_DIALECT_MAP[dialectId];
	const tableById = new Map(schema.tables.map((table) => [table.id, table]));
	const statements: string[] = [];

	for (const table of schema.tables) {
		const lines: string[] = table.columns.map((column) => '  ' + renderColumnDef(dialect, column));

		const pkColumns = table.columns.filter((c) => c.primaryKey).map((c) => c.name);
		if (pkColumns.length > 0) {
			lines.push(`  PRIMARY KEY (${pkColumns.map((c) => dialect.quoteIdentifier(c)).join(', ')})`);
		}

		if (dialect.inlineForeignKeys) {
			for (const relation of schema.relations.filter((r) => r.sourceTable === table.id)) {
				lines.push('  ' + renderForeignKeyClause(dialect, relation, tableById.get(relation.targetTable)));
			}
		}

		statements.push(`CREATE TABLE ${dialect.qualifyTableName(table)} (\n${lines.join(',\n')}\n);`);

		for (const index of table.indexes) {
			const cols = index.columns.map((c) => dialect.quoteIdentifier(c)).join(', ');
			statements.push(
				`CREATE ${index.unique ? 'UNIQUE ' : ''}INDEX ${dialect.quoteIdentifier(index.name)} ON ${dialect.qualifyTableName(table)} (${cols});`
			);
		}
	}

	if (!dialect.inlineForeignKeys) {
		for (const relation of schema.relations) {
			const sourceTable = tableById.get(relation.sourceTable);
			if (!sourceTable) continue;
			statements.push(
				`ALTER TABLE ${dialect.qualifyTableName(sourceTable)} ADD CONSTRAINT ${dialect.quoteIdentifier(relation.name)} ${renderForeignKeyClause(dialect, relation, tableById.get(relation.targetTable))};`
			);
		}
	}

	const header = [
		`-- Generated by SchemaLens (${dialect.id})`,
		'-- 型別/預設值是從 .dbschema 的自由文字 best-effort 推斷的，套用前請自己檢查一次。',
		''
	].join('\n');

	return header + statements.join('\n\n') + '\n';
}
